In [1]:
!pip install gym

Defaulting to user installation because normal site-packages is not writeable


In [2]:
import gym
import numpy as np 
import tensorflow as tf

C:\ProgramData\Anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [3]:
tensor = tf.constant([[1,2],[3,4]])

In [4]:
print("Tensor:")
print(tensor)

Tensor:
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [5]:
variable = tf.Variable(tf.zeros([2,2]))

In [6]:
print("\nvariable:")
print(variable)


variable:
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>


In [7]:
variable.assign_add(tf.ones([2,2]))

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [8]:
print("\nUpdated Variable:")
print(variable)


Updated Variable:
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>


In [9]:
import gym
import random
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import Dense, Flatten
# from tensorflow.keras.optimizers import Adam
# 
# 
# from rl.policy import BoltzmannQPolicy
# from rl.memory import SequentialMemory


env = gym.make("CartPole-v1", render_mode = "human")

states = env.observation_space.shape[0]
actions = env.action_space.n

print(states)
print(actions)



episodes = 10
for episode in range(1, episodes+1):
    state = env.reset()
    done = False
    score = 0

    while not done:
        action = random.choice([0, 1])
        obs, reward, terminated, truncated , info = env.step(action)
        
        score += reward
        env.render()

    print(f"Episode {episode}, Score: {score}")

env.close()


4
2


C:\Users\anike\AppData\Roaming\Python\Python39\site-packages\gym\utils\passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):
C:\Users\anike\AppData\Roaming\Python\Python39\site-packages\gym\envs\classic_control\cartpole.py:177: UserWarning: WARN: You are calling 'step()' even though this environment has already returned terminated = True. You should always call 'reset()' once you receive 'terminated = True' -- any further steps are undefined behavior.
  logger.warn(


KeyboardInterrupt: 

In [2]:
# Cartpole code 2

# classical gym
import gym
# instead of gym, import gymnasium
# import gymnasium as gym
import numpy as np
import time

# create environment
env = gym.make('CartPole-v1', render_mode='human')
# reset the environment,
# returns an initial state
(state, _) = env.reset()
# states are
# cart position, cart velocity
# pole angle, pole angular velocity
# render the environment
env.render()
# close the environment
# env.close()

# push cart in one direction
env.step(0)


# simulate the environment
episodeNumber = 100
timeSteps = 100

for episodeIndex in range(episodeNumber):
    initial_state = env.reset()
    print(episodeIndex)
    env.render()
    appendedObservations = []
    for timeIndex in range(timeSteps):
        print(timeIndex)
        random_action = env.action_space.sample()
        observation, reward, terminated, truncated, info = env.step(random_action)
        appendedObservations.append(observation)
        time.sleep(0.1)
        if (terminated):
            time.sleep(1)
            break
env.close()

0
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35


KeyboardInterrupt: 